# Generated by Django 5.2.6 on 2025-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sac',
            name='couleur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sac',
            name='taille',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sac',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sac',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
