# Generated by Django 5.2.6 on 2025-09-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_sac_couleur_sac_taille_alter_sac_nom_alter_sac_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sac',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='sac',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sac',
            name='taille',
        ),
        migrations.AlterField(
            model_name='sac',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='SacImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sacs_images/')),
                ('couleur', models.CharField(max_length=50)),
                ('sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.sac')),
            ],
        ),
    ]
