# Generated by Django 5.2.6 on 2025-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_remove_sac_couleur_remove_sac_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sac',
            name='image',
            field=models.ImageField(default='', upload_to='sacs/'),
            preserve_default=False,
        ),
    ]
